#!/bin/bash 

# based on https://tfswitch.warrensbox.com/Continuous-Integration/

echo "Installing tfswitch locally"

# Get the installer on to your machine
# wget -N -c https://raw.githubusercontent.com/warrensbox/terraform-switcher/release/install.sh
curl -O  https://raw.githubusercontent.com/warrensbox/terraform-switcher/release/install.sh


# Make installer executable
chmod 755 install.sh

# Install tfswitch in a location you have permission
./install.sh -b $(pwd)/.bin

# set custom bin path
CUSTOMBIN=$(pwd)/.bin

#Add custom bin path to PATH environment
export PATH=$CUSTOMBIN:$PATH

# $CUSTOMBIN/tfswitch -b $CUSTOMBIN/terraform

# terraform $*

curl -O https://github.com/aquasecurity/tfsec/releases/download/v1.18.0/tfsec_1.18.0_linux_amd64.tar.gz

ls ./ 

tar zxvf tfsec_1.18.0_linux_amd64.tar.gz

ls ./

ls tfsec_1.18.0_linux_amd64

ls tfsec_1.18.0_linux_amd64/bin 

tfsec_1.18.0_linux_amd64/bin/tfsec ./