apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-jenkins-pvc
  namespace: jenkins
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: my-jenkins-storage
  resources:
    requests:
      storage: 200Mi
