apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: jenkins
spec:
  ports:
    - name: "8080"
      port: 8080
      nodePort: 32080
  selector:
    app: jenkins
  type: NodePort